// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// AppCore APIs
class AppCoreAPI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AppCoreAPI(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AppCoreAPI.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void sendPointerEvent(
    double x,
    double y,
  ) {
    return _sendPointerEvent(
      x,
      y,
    );
  }

  late final _sendPointerEvent_ptr =
      _lookup<ffi.NativeFunction<_c_sendPointerEvent>>('sendPointerEvent');
  late final _dart_sendPointerEvent _sendPointerEvent =
      _sendPointerEvent_ptr.asFunction<_dart_sendPointerEvent>();
}

typedef _c_sendPointerEvent = ffi.Void Function(
  ffi.Float x,
  ffi.Float y,
);

typedef _dart_sendPointerEvent = void Function(
  double x,
  double y,
);
